apiVersion: v1
kind: Pod
metadata:
  name: postgresql
  labels:
    app.kubernetes.io/name: postgresql
spec:
  containers:
  - name: postgresql
    image:  postgres
    ports:
      - containerPort: 5432
    
    env:
            - name: POSTGRES_USER
              value: postgres

            - name: POSTGRES_PASSWORD
              value: postgres123

            - name: POSTGRES_DB
              value: axion