apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telemetry-deployment
  template:
    metadata:
      labels:
        app: telemetry-deployment
    spec:
      containers:
      - name: telemetry-deployment
        image: acrmicrodev567.azurecr.io/telemetry:v1
        
        ports:
        - containerPort: 8000

        env:
        - name: DATABASE_URL
          value: "postgresql://myuser:mypassword@postgresqlsvc:5432/mydatabase"                 
  